// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc2qqzmyItf5JNMSamqexO1LYUWjxcbvY',
    appId: '1:388778357826:web:dc8ea27bf33f7f021629db',
    messagingSenderId: '388778357826',
    projectId: 'water-app-ffb7c',
    authDomain: 'water-app-ffb7c.firebaseapp.com',
    storageBucket: 'water-app-ffb7c.appspot.com',
    measurementId: 'G-R08J2VVQ2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzNCOanz1C3B0gK3MrmG2tZQZg5gEIczM',
    appId: '1:388778357826:android:22a9d6872ed5b7a81629db',
    messagingSenderId: '388778357826',
    projectId: 'water-app-ffb7c',
    storageBucket: 'water-app-ffb7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW8Nd0YTpfC0jfGvl9_l1f7Z59HOyXwPA',
    appId: '1:388778357826:ios:0c881d88dae77ff21629db',
    messagingSenderId: '388778357826',
    projectId: 'water-app-ffb7c',
    storageBucket: 'water-app-ffb7c.appspot.com',
    iosBundleId: 'com.gmail.yp10731155',
  );
}
